# Example : the try block does not generate any error:
try:
    print("Hello")
except:
    print("Something went wrong")
else:
    print("Nothing went wrong")